from enum import Enum


class EventType(str, Enum):
    MODEL_INVOCATION = 'MODEL_INVOCATION'
    FALLBACK = 'FALLBACK'
    GUARDRAIL = 'GUARDRAIL'
    ROUTING = 'ROUTING'
    RATE_LIMIT = 'RATE_LIMIT'
    CACHE_HIT = 'CACHE_HIT'
    TOKEN_INPUT_LIMIT = 'TOKEN_INPUT_LIMIT'
    TOKEN_OUTPUT_LIMIT = 'TOKEN_OUTPUT_LIMIT'
    INPUT_TOKEN_PROCESSED = 'INPUT_TOKEN_PROCESSED'
    OUTPUT_TOKEN_PROCESSED = 'OUTPUT_TOKEN_PROCESSED'
    CACHE_INPUT_TOKENS = 'CACHE_INPUT_TOKENS'
    CACHE_OUTPUT_TOKENS = 'CACHE_OUTPUT_TOKENS'
    REQUEST = 'REQUEST'
