"""add groups

Revision ID: 1a2b1d01d33e
Revises: 3541b4cb5838
Create Date: 2025-08-18 05:47:06.676875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a2b1d01d33e'
down_revision: Union[str, Sequence[str], None] = '3541b4cb5838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pk_user_key'), 'user_key', type_='primary')
    op.create_primary_key(op.f('pk_user_key'), 'user_key', ['UUID'])
    op.create_table('group',
    sa.Column('UUID', sa.UUID(), nullable=False),
    sa.Column('NAME', sa.VARCHAR(), nullable=False),
    sa.Column('ROUTES', sa.VARCHAR(length=128), nullable=False),
    sa.Column('CREATED_AT', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('UPDATED_AT', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('UUID', name=op.f('pk_group'))
    )
    op.create_table('group_keys',
    sa.Column('GROUP_UUID', sa.UUID(), nullable=False),
    sa.Column('USER_KEY_UUID', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['GROUP_UUID'], ['group.UUID'], name=op.f('fk_group_keys_GROUP_UUID_group'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['USER_KEY_UUID'], ['user_key.UUID'], name=op.f('fk_group_keys_USER_KEY_UUID_user_key'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('GROUP_UUID', 'USER_KEY_UUID', name=op.f('pk_group_keys'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pk_user_key'), 'user_key', type_='primary')
    op.create_primary_key(op.f('pk_user_key'), 'user_key', ['UUID', 'EMAIL'])
    op.drop_table('group_keys')
    op.drop_table('group')
    # ### end Alembic commands ###
