"""init db

Revision ID: 3541b4cb5838
Revises:
Create Date: 2025-08-11 07:30:29.084960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3541b4cb5838'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_key',
    sa.Column('UUID', sa.UUID(), nullable=False),
    sa.Column('EMAIL', sa.VARCHAR(), nullable=False),
    sa.Column('HASHED_KEY', sa.VARCHAR(length=128), nullable=False),
    sa.Column('OBSCURED_KEY', sa.VARCHAR(length=128), nullable=False),
    sa.Column('CREATED_AT', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('UPDATED_AT', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('UUID', 'EMAIL', name=op.f('pk_user_key'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_key')
    # ### end Alembic commands ###
