"""group routes as table

Revision ID: 52b10f350046
Revises: ca3e44546368
Create Date: 2025-08-21 06:09:37.050297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52b10f350046'
down_revision: Union[str, Sequence[str], None] = 'ca3e44546368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_routes',
    sa.Column('GROUP_UUID', sa.UUID(), nullable=False),
    sa.Column('ROUTE_NAME', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['GROUP_UUID'], ['group.UUID'], name=op.f('fk_group_routes_GROUP_UUID_group'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('GROUP_UUID', 'ROUTE_NAME', name=op.f('pk_group_routes'))
    )
    op.drop_column('group', 'ROUTES')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('ROUTES', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_table('group_routes')
    # ### end Alembic commands ###
