"""rename user_key to key

Revision ID: ca3e44546368
Revises: 1a2b1d01d33e
Create Date: 2025-08-20 12:00:50.806426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca3e44546368'
down_revision: Union[str, Sequence[str], None] = '1a2b1d01d33e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key',
    sa.Column('UUID', sa.UUID(), nullable=False),
    sa.Column('ID', sa.VARCHAR(), nullable=False),
    sa.Column('HASHED_KEY', sa.VARCHAR(length=128), nullable=False),
    sa.Column('OBSCURED_KEY', sa.VARCHAR(length=128), nullable=False),
    sa.Column('CREATED_AT', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('UPDATED_AT', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('UUID', name=op.f('pk_key'))
    )
    op.drop_constraint(op.f('fk_group_keys_USER_KEY_UUID_user_key'), 'group_keys', type_='foreignkey')
    op.drop_table('user_key')
    op.add_column('group_keys', sa.Column('KEY_UUID', sa.UUID(), nullable=False))
    op.create_foreign_key(op.f('fk_group_keys_KEY_UUID_key'), 'group_keys', 'key', ['KEY_UUID'], ['UUID'], ondelete='CASCADE')
    op.drop_column('group_keys', 'USER_KEY_UUID')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_keys', sa.Column('USER_KEY_UUID', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_group_keys_KEY_UUID_key'), 'group_keys', type_='foreignkey')
    op.create_foreign_key(op.f('fk_group_keys_USER_KEY_UUID_user_key'), 'group_keys', 'user_key', ['USER_KEY_UUID'], ['UUID'], ondelete='CASCADE')
    op.drop_column('group_keys', 'KEY_UUID')
    op.create_table('user_key',
    sa.Column('UUID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('EMAIL', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('HASHED_KEY', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('OBSCURED_KEY', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('CREATED_AT', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('UPDATED_AT', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('UUID', name=op.f('pk_user_key'))
    )
    op.drop_table('key')
    # ### end Alembic commands ###
