{{- if or (not .Values.clickhouse.auth.username.existingSecret) (not .Values.clickhouse.auth.password.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-ch-auth
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not .Values.clickhouse.auth.username.existingSecret }}
  username: {{ .Values.clickhouse.auth.username.value | b64enc | quote }}
  {{- end }}
  {{- if not .Values.clickhouse.auth.password.existingSecret }}
  password: {{ .Values.clickhouse.auth.password.value | b64enc | quote }}
  {{- end }}
{{- end }}