{{- if and .Values.metricsWorker.notifications.sendgrid.enabled (not .Values.metricsWorker.notifications.sendgrid.apiKey.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-sendgrid
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
type: Opaque
data:
  sendgrid-api-key: {{ .Values.metricsWorker.notifications.sendgrid.apiKey.value | b64enc | quote }}
{{- end }}
