{{- if not .Values.gateway.secrets.fromSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gateway.fullname" . }}-sec
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
type: Opaque
data:
  secrets.yaml: {{- toYaml .Values.gateway.secrets.plainSecrets | b64enc | quote }}
{{- end }}