-- +goose Up
ALTER TABLE default.event
    ADD COLUMN IF NOT EXISTS MODEL_ID LowCardinality(String) DEFAULT '',
    ADD COLUMN IF NOT EXISTS MODEL_TYPE LowCardinality(String) DEFAULT '',
    ADD COLUMN IF NOT EXISTS CACHE_TYPE LowCardinality(String) DEFAULT '',
    ADD COLUMN IF NOT EXISTS IS_CACHED_TOKENS Bool DEFAULT false,
    ADD COLUMN IF NOT EXISTS TARGET LowCardinality(String) DEFAULT '',
    ADD COLUMN IF NOT EXISTS FALLBACK LowCardinality(String) DEFAULT '',
    ADD COLUMN IF NOT EXISTS GUARDRAIL_NAME LowCardinality(String) DEFAULT '',
    ADD COLUMN IF NOT EXISTS GUARDRAIL_TYPE LowCardinality(String) DEFAULT '',
    ADD COLUMN IF NOT EXISTS GUARDRAIL_WHERE LowCardinality(String) DEFAULT '',
    ADD COLUMN IF NOT EXISTS GUARDRAIL_PARAMS String DEFAULT '',
    ADD COLUMN IF NOT EXISTS GUARDRAIL_BEHAVIOR LowCardinality(String) DEFAULT '',
    ADD COLUMN IF NOT EXISTS IS_JUDGE Bool DEFAULT false;

-- +goose Down
ALTER TABLE default.event
    DROP COLUMN IF EXISTS MODEL_ID,
    DROP COLUMN IF EXISTS MODEL_TYPE,
    DROP COLUMN IF EXISTS CACHE_TYPE,
    DROP COLUMN IF EXISTS IS_CACHED_TOKENS,
    DROP COLUMN IF EXISTS TARGET,
    DROP COLUMN IF EXISTS FALLBACK,
    DROP COLUMN IF EXISTS GUARDRAIL_NAME,
    DROP COLUMN IF EXISTS GUARDRAIL_TYPE,
    DROP COLUMN IF EXISTS GUARDRAIL_WHERE,
    DROP COLUMN IF EXISTS GUARDRAIL_PARAMS,
    DROP COLUMN IF EXISTS GUARDRAIL_BEHAVIOR,
    DROP COLUMN IF EXISTS IS_JUDGE;
