-- +goose Up
ALTER TABLE default.event
    ADD COLUMN IF NOT EXISTS ROUTING_NAME LowCardinality(String) DEFAULT '',
    ADD COLUMN IF NOT EXISTS ROUTING_SELECTED_MODEL_ID LowCardinality(String) DEFAULT '';

-- +goose Down
ALTER TABLE default.event
    DROP COLUMN IF EXISTS ROUTING_NAME,
    DROP COLUMN IF EXISTS ROUTING_SELECTED_MODEL_ID;
