-- +goose Up
ALTER TABLE default.event
    ADD COLUMN IF NOT EXISTS PROJECT_UUID Nullable(UUID),
    ADD COLUMN IF NOT EXISTS PROJECT_NAME LowCardinality(String) DEFAULT '';

ALTER TABLE default.request_event
    ADD COLUMN IF NOT EXISTS PROJECT_UUID Nullable(UUID),
    ADD COLUMN IF NOT EXISTS PROJECT_NAME LowCardinality(String) DEFAULT '';

-- +goose Down
ALTER TABLE default.event
    DROP COLUMN IF EXISTS PROJECT_UUID,
    DROP COLUMN IF EXISTS PROJECT_NAME;

ALTER TABLE default.request_event
    DROP COLUMN IF EXISTS PROJECT_UUID,
    DROP COLUMN IF EXISTS PROJECT_NAME;
